### ISSUE TITLE
Crashes when deleting all flares

### ISSUE THREAD

**Issue by RileyWClarke** [jradavenport/FBEYE#10]
% FBEYE_REMOVE: ERROR - Cannot delete all elements from a vector
% Execution halted at: FBEYE_DELFLARE     17 /Users/clarker2/idl/FBEYE/fbeye/fbeye_delflare.pro
%                      FBEYE             723 /Users/clarker2/idl/FBEYE/fbeye/fbeye.pro
%                      $MAIN$

**Comment by jradavenport** [comment]
This was happening for a variety of silly reasons, namely when arrays had a "null" event (event ID = -1) they were getting shown as flares that ended on the first data point. The latest version solves this in a few ways:
1. don't show "null" events (were showing up as flare ends at the start of the data)
2. dont allow deleting flare events outside of data range
